//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGameCorner.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardGameCorner.Resources.Language.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to my list.
        /// </summary>
        internal static string AddToList {
            get {
                return ResourceManager.GetString("AddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load games. Please try again..
        /// </summary>
        internal static string APIErrorMessage {
            get {
                return ResourceManager.GetString("APIErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Deals.
        /// </summary>
        internal static string Best_Deals {
            get {
                return ResourceManager.GetString("Best Deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Image.
        /// </summary>
        internal static string Capture_Image {
            get {
                return ResourceManager.GetString("Capture Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Comparision.
        /// </summary>
        internal static string Card_Comparision {
            get {
                return ResourceManager.GetString("Card Comparision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Details.
        /// </summary>
        internal static string Card_Details {
            get {
                return ResourceManager.GetString("Card Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Not Found.
        /// </summary>
        internal static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose condition/grade....
        /// </summary>
        internal static string Choose_condition_grade {
            get {
                return ResourceManager.GetString("Choose condition/grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language....
        /// </summary>
        internal static string Choose_Language {
            get {
                return ResourceManager.GetString("Choose Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will pick your package. Click Here!.
        /// </summary>
        internal static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to contacted in case of:.
        /// </summary>
        internal static string Contacted {
            get {
                return ResourceManager.GetString("Contacted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load data:.
        /// </summary>
        internal static string DataLoadErrorMessage {
            get {
                return ResourceManager.GetString("DataLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this card?.
        /// </summary>
        internal static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this Email already exists..
        /// </summary>
        internal static string DuplicateUserNameMessage {
            get {
                return ResourceManager.GetString("DuplicateUserNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ST Edition.
        /// </summary>
        internal static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email .
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        internal static string EmailEmptyError {
            get {
                return ResourceManager.GetString("EmailEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset request failed: Failed to send reset link..
        /// </summary>
        internal static string EmailFailed {
            get {
                return ResourceManager.GetString("EmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is required..
        /// </summary>
        internal static string EmailRequiredMessage {
            get {
                return ResourceManager.GetString("EmailRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your list is empty. Add items to see them here..
        /// </summary>
        internal static string EmptyListMessage {
            get {
                return ResourceManager.GetString("EmptyListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string EmptyListTitle {
            get {
                return ResourceManager.GetString("EmptyListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable internet connection.
        /// </summary>
        internal static string Enable_internet_connection {
            get {
                return ResourceManager.GetString("Enable internet connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a game.
        /// </summary>
        internal static string Error_GameNotSelected {
            get {
                return ResourceManager.GetString("Error_GameNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login first.
        /// </summary>
        internal static string Error_LoginRequired {
            get {
                return ResourceManager.GetString("Error_LoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cards found for game: .
        /// </summary>
        internal static string Error_NoCardsFound {
            get {
                return ResourceManager.GetString("Error_NoCardsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to place order. Please try again..
        /// </summary>
        internal static string Error_OrderFailed {
            get {
                return ResourceManager.GetString("Error_OrderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add product..
        /// </summary>
        internal static string ErrorAddProduct {
            get {
                return ResourceManager.GetString("ErrorAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load games. Please try again..
        /// </summary>
        internal static string ErrorLoadingGames {
            get {
                return ResourceManager.GetString("ErrorLoadingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading data. Please try again..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve product details..
        /// </summary>
        internal static string ErrorRetrieveProduct {
            get {
                return ResourceManager.GetString("ErrorRetrieveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve authentication token..
        /// </summary>
        internal static string ErrorRetrieveToken {
            get {
                return ResourceManager.GetString("ErrorRetrieveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the Required fields.
        /// </summary>
        internal static string FillRequiredFieldsMessage {
            get {
                return ResourceManager.GetString("FillRequiredFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Code.
        /// </summary>
        internal static string Fiscal_Code {
            get {
                return ResourceManager.GetString("Fiscal Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        internal static string ForgotPasswordEmailLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Details.
        /// </summary>
        internal static string Game_Details {
            get {
                return ResourceManager.GetString("Game Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenericErrorMessage.
        /// </summary>
        internal static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how you want to get paid.
        /// </summary>
        internal static string GetPaid {
            get {
                return ResourceManager.GetString("GetPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the IBAN code for the bank transfer.
        /// </summary>
        internal static string IBNCode {
            get {
                return ResourceManager.GetString("IBNCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection has been restored.
        /// </summary>
        internal static string Internet_connection_restored {
            get {
                return ResourceManager.GetString("Internet connection restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Restored.
        /// </summary>
        internal static string Internet_Restored {
            get {
                return ResourceManager.GetString("Internet Restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this Your Card?.
        /// </summary>
        internal static string Is_this_Your_Card_ {
            get {
                return ResourceManager.GetString("Is this Your Card?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Last_Name {
            get {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your card list is empty..
        /// </summary>
        internal static string ListEmptyMsg {
            get {
                return ResourceManager.GetString("ListEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card List Empty.
        /// </summary>
        internal static string ListEmptyTitle {
            get {
                return ResourceManager.GetString("ListEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed: Invalid credentials.
        /// </summary>
        internal static string Login_failed {
            get {
                return ResourceManager.GetString("Login failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to log in to access this page. Would you like to log in?.
        /// </summary>
        internal static string LoginRequiredMessage {
            get {
                return ResourceManager.GetString("LoginRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Required.
        /// </summary>
        internal static string LoginRequiredTitle {
            get {
                return ResourceManager.GetString("LoginRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        internal static string LogoutConfirmationMessage {
            get {
                return ResourceManager.GetString("LogoutConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutConfirmationTitle {
            get {
                return ResourceManager.GetString("LogoutConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully logged out..
        /// </summary>
        internal static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged Out.
        /// </summary>
        internal static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyAccount.
        /// </summary>
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyList.
        /// </summary>
        internal static string MyList {
            get {
                return ResourceManager.GetString("MyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No! I will try again.
        /// </summary>
        internal static string No__I_will_try_again {
            get {
                return ResourceManager.GetString("No! I will try again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet.
        /// </summary>
        internal static string No_Internet {
            get {
                return ResourceManager.GetString("No Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found. Try a different search term..
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products found..
        /// </summary>
        internal static string notFoundProduct {
            get {
                return ResourceManager.GetString("notFoundProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        internal static string PasswordEmptyError {
            get {
                return ResourceManager.GetString("PasswordEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password .
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        internal static string PasswordRequiredMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must contain at least one digit (&apos;0&apos;-&apos;9&apos;)..
        /// </summary>
        internal static string PasswordRequiresDigitMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresDigitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must contain at least one lowercase letter (&apos;a&apos;-&apos;z&apos;)..
        /// </summary>
        internal static string PasswordRequiresLowerMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresLowerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must contain at least one non-alphanumeric character..
        /// </summary>
        internal static string PasswordRequiresNonAlphanumericMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must use at least 1 different character..
        /// </summary>
        internal static string PasswordRequiresUniqueCharsMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresUniqueCharsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must contain at least one uppercase letter (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        internal static string PasswordRequiresUpperMessage {
            get {
                return ResourceManager.GetString("PasswordRequiresUpperMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset link has been sent to your email.
        /// </summary>
        internal static string PasswordResetSuccessMessage {
            get {
                return ResourceManager.GetString("PasswordResetSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be at least 7 characters long..
        /// </summary>
        internal static string PasswordTooShortMessage {
            get {
                return ResourceManager.GetString("PasswordTooShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the E-mail address for your PayPal account:.
        /// </summary>
        internal static string PaypalEmail {
            get {
                return ResourceManager.GetString("PaypalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IBAN code.
        /// </summary>
        internal static string PIBNCode {
            get {
                return ResourceManager.GetString("PIBNCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        internal static string PlaceOrder {
            get {
                return ResourceManager.GetString("PlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter PayPal email.
        /// </summary>
        internal static string PPaypalEmail {
            get {
                return ResourceManager.GetString("PPaypalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product added to your list!.
        /// </summary>
        internal static string ProductAddedToList {
            get {
                return ResourceManager.GetString("ProductAddedToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product updated to your list!.
        /// </summary>
        internal static string ProductUpdated {
            get {
                return ResourceManager.GetString("ProductUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your message here....
        /// </summary>
        internal static string PStaffMsg {
            get {
                return ResourceManager.GetString("PStaffMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed. Please try again..
        /// </summary>
        internal static string RegistrationFailedMessage {
            get {
                return ResourceManager.GetString("RegistrationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email *.
        /// </summary>
        internal static string REmail {
            get {
                return ResourceManager.GetString("REmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password *.
        /// </summary>
        internal static string RPlaceholder {
            get {
                return ResourceManager.GetString("RPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan with camera.
        /// </summary>
        internal static string Scan_with_camera {
            get {
                return ResourceManager.GetString("Scan with camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        internal static string Search_Result {
            get {
                return ResourceManager.GetString("Search Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Reset Link.
        /// </summary>
        internal static string SendResetLink {
            get {
                return ResourceManager.GetString("SendResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site credit.
        /// </summary>
        internal static string Site_credit {
            get {
                return ResourceManager.GetString("Site credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any messages for the staff.
        /// </summary>
        internal static string StaffMsg {
            get {
                return ResourceManager.GetString("StaffMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Order placed successfully!.
        /// </summary>
        internal static string Success_OrderPlaced {
            get {
                return ResourceManager.GetString("Success_OrderPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Add to List!.
        /// </summary>
        internal static string SuccessAddedToList {
            get {
                return ResourceManager.GetString("SuccessAddedToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card added to your collection!.
        /// </summary>
        internal static string successmsg {
            get {
                return ResourceManager.GetString("successmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully.
        /// </summary>
        internal static string SuccessUpdate {
            get {
                return ResourceManager.GetString("SuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Try Again!.
        /// </summary>
        internal static string tryAgain {
            get {
                return ResourceManager.GetString("tryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update List.
        /// </summary>
        internal static string UpdateList {
            get {
                return ResourceManager.GetString("UpdateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        internal static string Upload_Image {
            get {
                return ResourceManager.GetString("Upload Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty.
        /// </summary>
        internal static string UsernameEmptyError {
            get {
                return ResourceManager.GetString("UsernameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and Password cannot be empty.
        /// </summary>
        internal static string UserPassEmpty {
            get {
                return ResourceManager.GetString("UserPassEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format. Please enter a valid email address..
        /// </summary>
        internal static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number.
        /// </summary>
        internal static string VAT_Number {
            get {
                return ResourceManager.GetString("VAT Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Card Game Corner!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes! Add to my list.
        /// </summary>
        internal static string Yes__Add_to_my_list {
            get {
                return ResourceManager.GetString("Yes! Add to my list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesMsg {
            get {
                return ResourceManager.GetString("YesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Picture.
        /// </summary>
        internal static string Your_Picture {
            get {
                return ResourceManager.GetString("Your Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.
        /// </summary>
        internal static string z {
            get {
                return ResourceManager.GetString("z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        internal static string ZIP {
            get {
                return ResourceManager.GetString("ZIP", resourceCulture);
            }
        }
    }
}
